Repository khulnasoft/ml-workspace, pull requests merged in 2024-11, with the labels that each got.

#4 Update Dockerfile
  .github/workflows/issue-manager.yml
  Dockerfile
Labels: enhancement, dependencies, Review effort [1-5]: 4

#10 Fix code scanning alert no. 5: Unsafe shell command constructed from library input
  resources/jupyter/extensions/tooling-extension/jupyter_tooling/tooling_handler.py
Labels: Review effort [1-5]: 1, Possible security concern

#11 Fix code scanning alert no. 1: Log injection
  resources/novnc/app/ui.js
Labels: Review effort [1-5]: 2
